name: Deploy on Release
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 224
          script: |
            echo "Starting deployment..."
            pkill -f "ssh-application/server" || true
            
            
            cd ~/ssh-application
            
            echo "Downloading release..."
            curl -L -o ssh-app-linux-amd64.tar.gz \
              "https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/ssh-app-linux-amd64.tar.gz"
            
            echo "Extracting..."
            tar -xzvf ssh-app-linux-amd64.tar.gz
            mv linux-amd64/server ./server
            rm -rf linux-amd64 ssh-app-linux-amd64.tar.gz
            
            echo "Starting server..."
            setsid ./server > server.log 2>&1 &
            sleep 2
            echo "Done!"
